### ISSUE TITLE
TYPO3 6.2 Install fail a step 2 Database connection

### ISSUE THREAD

**Issue by WebPam** [crinis/typo3-docker#3]
Hi,
Thank your for your work, it looks great !
Still It seems I need a lite help ! ;)

I have a docker droplet at Digital Ocean
I have installed TYPO3 6.2 with docker compose.
Everything went fine.
I have kept the defaut login / password from https://github.com/crinis/typo3-docker/tree/master/6.2)/docker-compose.yml
When I acces to TYPO3 at http://46.101.154.102/typo3/install/ I am blocked on step 2 : " Database connect not successful
Connecting to the database with given settings failed. Please check."
I have tried to connect directly to mysql within the container  62-mysql-1 with the defaut login / password, it works.
Any idea how to fix it ?

**Comment by crinis** [comment]
There is no automated setup for TYPO3 6.2. Did you specify the database hostname properly during setup? If you use the default docker-compose.yml it should be "mysql". 

![image](https://user-images.githubusercontent.com/6907942/188330581-3c1bb6a3-f8b0-4548-9252-5e7e597816a0.png)

**Comment by WebPam** [comment]
Thank's a lot ! It is working perfectly :)

**Comment by WebPam** [comment]
Solved !

**Comment by WebPam** [comment]
Hi, 
Do you think it could be helpfull to mention the database hostname used for TYPO3 6.2 in readme.txt ?
All the best
Sasha :)

**Comment by crinis** [comment]
This is well [documented](https://docs.docker.com/compose/networking/) and only relevant for TYPO3 6.2 which is heavily outdated and should not be used for new projects.
